services:
  ari:
    build: ./ari
    depends_on:
      - asterisk
    networks:
      - asterisknet
  asterisk:
    build: .
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "8088:8088/tcp"
    volumes:
      - ./etc/asterisk:/opt/asterisk/etc/asterisk
    networks:
      - asterisknet
networks:
  asterisknet:
    driver: bridge
